version: '2.0'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: api
    restart: always
    env_file: .env-docker
    ports:
      - "3001:3000"
    networks:
      - app-network
    depends_on:
      - iberedb
    command: ["./wait-for-it.sh", "-t", "0", "iberedb:3306", "--", "npm","start", ]
  iberedb:
    image: mysql:5.7
    restart: always
    container_name: iberedb
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'senha'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - iberedb:/var/lib/mysql
    networks:
      - app-network
# Networks
networks:
  app-network:
    driver: bridge
# Names our volume
volumes:
  iberedb: